### ISSUE TITLE
Code request

### ISSUE THREAD

**Issue by PoaStell** [robertpiira/ingrid#7]
I really like the Ingrid 'kitten' page and i'd like adopt/adapt it for a current project. Assuming you would be  happy with that... I can't find the Ingrid 1.0 css code, can you point me to it please? (NB i'm new user of github). Thanks

**Comment by cs102** [comment]
try... this https://github.com/robertpiira/ingrid/tree/ingrid_1.0  

happy coding

**Comment by PoaStell** [comment]
So far so good! Thanks a lot. If the project flourishes I'll send you the addresses.

**Comment by robertpiira** [comment]
Thanks @cs102 for jumping in. @PoaStell Good luck with your new project! Let us know how it goes :-)
